### ISSUE TITLE
Create Ubuntu 20.04 base image

### ISSUE THREAD

**Issue by robertopreste** [simphony/simphony-remote-docker-base#8]
The [ProMo](https://gitlab.cc-asp.fraunhofer.de/MarketPlace/simphony-remote-docker-promo) software image needs to be built using an Ubuntu 20.04 base image, for requirements reasons (it requires `dlite` which is only available for Python 3.7+, which in turn is available on Ubuntu 20.04 by default).

**Comment by peterzahemszky** [comment]
> it requires `dlite` which is only available for Python 3.7+

According to https://github.com/heinz-preisig/ProMo-packages-OntologyBuilder/blob/master/EMMO_Integration/demo/horizontal/README.md, the DLite requirement is [jesper-friis/DLite](https://github.com/jesper-friis/DLite) on GitHub. The [`dlite`](https://pypi.org/project/dlite/) package on PyPI is a different one.

In light of this, the strict Python 3.7 requirement can be made more lenient; from https://github.com/jesper-friis/DLite#runtime-dependencies:
> Python 3 development libraries, optional (needed by Python bindings)

That is to say, any Python 3 version is fine, it doesn't have to be 3.7.

**Comment by peterzahemszky** [comment]
This is not of high priority right now, so I'm closing this ticket. We can reopen it later if necessary
